### ISSUE TITLE
Bouton "Nouvelle Affaire" : Le montant TTC est envoyé au lieu du montant HT 

### ISSUE THREAD

**Issue by daamien** [FHenry/lead#1]
1- Créer et valider une propale
2- Cliquer sur le bouton "Nouvelle Affaire"

Sur la /custom/lead/lead/card.php?action=create le formulaire s'affiche avec les champs prérempli mais le champs "Montant HT" (amount_guess) reprend la valeur du total TTC de la propale

**Comment by FHenry** [comment]
fix in develop
