### ISSUE TITLE
Upgrade to Dolibarr 3.8 with the module already installed

### ISSUE THREAD

**Issue by FHenry** [FHenry/lead#11]
If you do so, please download the last module version install it and desactivate lead and activate lead again.
Into Dolibarr 3.8 there is a new table ith the same name as lead table. I have to reproduce the same model in the lead module version 1.7

**Comment by rdoursenaud** [comment]
I think the module should be deactivated before 3.8 upgrade because the upgrade won't work with lead tables installed because of the schema mismatch.
