### ISSUE TITLE
Module lead 1.9 not working in Dolibarr 3.8.2 / 3.8.3

### ISSUE THREAD

**Issue by Sarlandi** [FHenry/lead#16]
Hello,
I wanted to point out that the LEAD module 1.9 does not work in the sleepers Dolibarr 3.8.2 and 3.8.3.
The module is installed correctly, but does not save any changes on additional fields, from the error message.
At present the only possible combination is LEAD module Dolibarr 1.7 and 3.8.1
Thank you
Sandro Orlandi

**Comment by FHenry** [comment]
I can't reproduce on Demo web site http://demo.open-concept.pro/dolibarr/htdocs/custom/lead/lead/card.php?id=123
I can edit and update extrafields named Attribut des test
Lead 1.7 and Dolibarr 3.8.3

**Comment by Sarlandi** [comment]
LEAD module Dolibarr 1.7 and 3.8.3 would be perfect

Greetings

Sandro Orlandi
