### ISSUE TITLE
Display more details in the lead list on /contrat/card.php

### ISSUE THREAD

**Issue by daamien** [FHenry/lead#17]
At the bottom of the contract card, the lead box provides the list of all attached leads. 

For now the list contains only the id of the lead. For example :

LEA-1401-1288 
LEA-1510-5580 

There's enough to display more info like this (pardon my French):

LEA-1401-1288   Vente de 2 tonnes de carottes ( Gagné - Formation )
LEA-1510-5580   Entretien de la piscine de M. Michu ( Perdu - Assistance )

and order the list by date :)

**Comment by ghost** [comment]
fix with version 1.10 (same as branch master)
