### ISSUE TITLE
Remove contract already attached form the contract select box in /lead/lead/card.php

### ISSUE THREAD

**Issue by daamien** [FHenry/lead#18]
In  the contract section of the lead card, there's a dropdown menu to select a contract and attach the lead to this contract. 

If a contract is already attached to the lead, the contract continues to appear in the dropdown menu. This confusing. The dropdown menu should contains only contracts that are not already attached to the lead.

**Comment by FHenry** [comment]
There is an option in admin page that allow you to attach on contract to mutiple lead. If I remember, this option was added on your request. If you set this option to OFF, only "free" contract will be available in this list.

**Comment by daamien** [comment]
I'm reopening this one :-)

**Comment by daamien** [comment]
https://github.com/FHenry/lead/pull/20
